/**
 * Formats weekly ingredients data into a readable text format
 * for copying to clipboard or sharing via WhatsApp
 */

interface PlannedDay {
  dayOfWeek: number;
  date: string;
  slots: string[];
}

interface MealIngredient {
  mealId: number;
  title: string;
  rating: number;
  recipeText: string | null;
  imageUrl: string | null;
  plannedDays: PlannedDay[];
  earliestDay: number;
}

export interface WeeklyIngredientsData {
  weekStartDate: string;
  meals: MealIngredient[];
}

/**
 * Generates formatted text from weekly ingredients data
 * @param data Weekly ingredients data with meals and their planned days
 * @returns Formatted text string ready for copying or sharing
 */
export function generateIngredientsText(data: WeeklyIngredientsData): string {
  const { weekStartDate, meals } = data;

  if (meals.length === 0) {
    return 'No meals planned for this week.';
  }

  let text = `WEEKLY MEAL PLAN - ${weekStartDate}\n`;
  text += '═'.repeat(50) + '\n\n';

  meals.forEach((meal, index) => {
    // Meal header
    text += `${index + 1}. ${meal.title.toUpperCase()}\n`;
    text += `   Rating: ${'⭐'.repeat(meal.rating)}\n`;

    // Days planned
    text += `   Scheduled:\n`;
    meal.plannedDays.forEach((day) => {
      const slots = day.slots
        .map((s) => s.charAt(0) + s.slice(1).toLowerCase())
        .join(', ');
      text += `   • ${day.date} (${slots})\n`;
    });

    // Recipe/ingredients
    text += `\n   INGREDIENTS:\n`;
    if (meal.recipeText) {
      meal.recipeText.split('\n').forEach((line) => {
        text += `   ${line}\n`;
      });
    } else {
      text += `   (No ingredients listed)\n`;
    }

    text += '\n' + '─'.repeat(50) + '\n\n';
  });

  text += 'Generated by Meal Planner App';

  return text;
}
